Add `formatUser` option.
fastify/fastify-jwt pull request #131
Opened 2021-01-10 00:11 UTC by wtgtybhertgeghgtwtg

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Closes #130.  Please let me know if there's anything I should correct.

2021-01-10 09:26 UTC, mcollina requested changes
The new types require testing.

2021-01-10 11:21 UTC, wtgtybhertgeghgtwtg commented
Sorry about that.  I've updated with a test showing the configuration accepts the new key, but, with the limitation on module merging, I do not believe I can write one that shows that the `payload` of `formatUser` is of type `FastifyJWT.payload`.  Please let me know if this is insufficient.

2021-01-11 09:16 UTC, mcollina commented on test.js
> +})
I know most of the other tests uses promises, but it would be better if we use async/await for all the new ones.

2021-01-11 17:39 UTC, wtgtybhertgeghgtwtg commented on jwt.test-d.ts
> +  formatUser: payload => ({ name: 'userName' })
I had considered that, but, with the limitation on module merging, `payload` will be `string | object | Buffer`, and I was not sure if the potential solution
```js
  formatUser: payload => {
    const objectPayload = typeof payload === 'string'
      ? JSON.parse(payload)
      : Buffer.isBuffer(payload)
        ? JSON.parse(payload.toString())
        : payload;
    return { name: objectPayload.userName }
  }
```
would be clear.  I have pushed a commit with this.  Please let me know if it is acceptable.

2021-01-11 22:30 UTC, mcollina approved these changes
lgtm

2021-01-11 23:03 UTC, Eomm commented on README.md
> +#### Example with formatted user
```suggestion
#### Example with formatted user
You may customize the `request.user` object setting a custom sync function as parameter:

```

2021-01-11 23:11 UTC, Eomm approved these changes

2021-01-11 23:11 UTC, merged

2021-01-11 23:31 UTC, wtgtybhertgeghgtwtg commented
Thank you for merging.

2021-01-12 09:17 UTC, Eomm commented
Thank you to you for this useful feature 😄