Change decorator name
fastify/fastify-jwt pull request #229
Opened 2022-05-27 12:59 UTC by sergioalmela

Changed decorator name to avoid conflict with @fastify/passport plugin using the same decorator

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-05-27 13:03 UTC, jsumners reviewed
I'd recommend making it configurable instead of this semver hard change.

2022-05-27 14:09 UTC, mcollina requested changes
Can you please add a unit test?
AS @jsumners said, make it configurable.

2022-05-27 21:02 UTC, sergioalmela commented
> Can you please add a unit test? AS @jsumners said, make it configurable.

Done, hope it's ok now

2022-05-27 21:19 UTC, mcollina requested changes
Can you please add docs in the readme?

2022-05-27 21:19 UTC, mcollina commented on jwt.js
> +  const jwtDecoratorName = process.env.JWT_DECORATOR_NAME || 'user'
please use an option to the plugin, not an env variable.

2022-05-28 11:14 UTC, jsumners commented on test/jwt.test.js
> +test('decorator name should work after being changed in the options', async function (t) {
This test is missing an assertion that the custom decorator name is present.

2022-05-30 09:13 UTC, mcollina approved these changes
lgtm

2022-05-30 09:13 UTC, merged

2022-05-30 11:12 UTC, jsumners reviewed
Dammit. Stupid phone client never sent this review.