feat: verifier-only mode impl and tests
fastify/fastify-jwt pull request #293
Opened 2023-06-13 11:48 UTC by maslennikov

If the implementation is good to go, I'll add changes to the docs.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-06-13 12:45 UTC, mcollina approved these changes
lgtm

2023-06-13 13:02 UTC, maslennikov commented
@mcollina good! i'll proceed with changes to the docs then

2023-06-13 14:39 UTC, maslennikov commented
@mcollina code, types, tests, and docs are ready

2023-06-16 08:59 UTC, maslennikov commented
Hello @mcollina! Are there any issues with this PR? Does it need some extra work to get a go?

2023-06-23 18:24 UTC, mcollina approved these changes
lgtm

2023-06-25 10:30 UTC, Fdawgs requested changes

2023-06-25 10:30 UTC, Fdawgs commented on README.md
> +of `sign` functionality.
```suggestion
In cases where your incoming JWT tokens are issued by a trusted external
service, and you need only to verify their signature without issuing, there is
an option to configure `fastify-jwt` in *verify-only* mode by passing the
`secret` object containing only a public key: `{ public }`.

When only a public key is provided, decode and verification functions will work as
described below, but an exception will be thrown at an attempt to use any form
of `sign` functionality.
```

2023-06-25 10:31 UTC, Fdawgs approved these changes

2023-06-25 10:34 UTC, merged