Fix onRequest hook documentation
fastify/fastify-jwt pull request #302
Opened 2023-08-09 22:34 UTC by mattiapv

Added missing `async` and `await` keywords, `try...catch` block. This prevents server crashes caused by missing `await` on `jwtVerify()` function.

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-08-10 11:49 UTC, mcollina requested changes
None of this are needed, why did you add them?

2023-08-10 13:41 UTC, mattiapv commented
> None of this are needed, why did you add them?

Because without awaiting `jwtVerify()` the server crash.

You can try the [cookie](https://github.com/fastify/fastify-jwt#cookie) or the [onlyCookie](https://github.com/fastify/fastify-jwt#cookie) example.

If you make a call to `http://localhost:3000/verifyCookie` the server crash.

If I add `await request.jwtVerify()`, I get back an error and the server doesn't crash.

2023-08-10 16:17 UTC, Eomm commented on README.md
> +fastify.addHook('onRequest', async (request) => {
as before

2023-08-10 16:17 UTC, Eomm commented on README.md
> +    await request.jwtVerify({onlyCookie: true})
this seems a doc error:

it should be
```
(request) => {
  return request.jwtVerify({ onlyCookie: true })
}
```

2023-08-10 17:18 UTC, mattiapv commented on README.md
> +});
I would keep arrow function, my mistake sorry.

2023-08-10 17:19 UTC, mattiapv commented on README.md
> +    await request.jwtVerify({onlyCookie: true})
I would it as

```js
fastify.addHook('onRequest', (request) =>
  request.jwtVerify({ onlyCookie: true })
);
```

2023-08-13 06:10 UTC, Eomm approved these changes

2023-10-04 08:45 UTC, mcollina approved these changes
lgtm

2023-10-04 08:45 UTC, merged